# Generated by Django 4.2.6 on 2023-10-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emissions',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Date_Created', models.DateField()),
                ('Accounting_Period', models.CharField(max_length=255)),
                ('Scope1', models.IntegerField(blank=True, null=True)),
                ('Scope2', models.IntegerField(blank=True, null=True)),
                ('Scope3', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
